--DROP TABLE SP_UBT_GETLOCATIONINVOICE;


CREATE TABLE SP_UBT_GETLOCATIONINVOICE (
    LOCDISPLAYID STRING,
    AGENTINVOICE_INVID STRING,
    AGENTINVOICE_FINIDN STRING,
    AGENTINVOICE_PRODUCTID STRING,
    SALES_TYPE STRING,
    TOTALCOUNT INT,
    AMOUNT DOUBLE,
    PROCDATE STRING,
    X_ETL_NAME STRING,
    X_RECORD_INSERT_TS TIMESTAMP_NTZ,
    X_RECORD_UPDATE_TS TIMESTAMP_NTZ
);
